export const dataList = [
  {},
  {
    heading: "Distribution Of Skin Lesions",
    opt: ["Generalised", "Limited", "Hands & Feet", "Herpetiform"],
    mapping: ["Generalised", "Limited", "Hands & Feet", "Herpetiform"],
    imgs: ["DL1", "DL2", "DL3", "DL4"],
    size: ["23%","23%","23%","23%"],
    cardheight: ["500px"],
    imageheight: ["auto"],
    subtitle: ["Generalised", "Limited", "Hands & feet", "Herpetiform"],
    title: [""],
    margintop: ["2.5rem", "3rem", "1rem", "1.5rem"],
    singleImg: [""],
    id: ["1"],
  },
  {
    heading: "Excess Granulation Tissue",
    opt: ["Absent", "Present"],
    mapping: ["-", "+"],
    imgs: ["EG10", "EG4"],
    size: ["30%","68%"],
    cardheight: ["100%"],
    imageheight: ["98.5%"],
    subtitle: ["", "", "", "", ""],
    title: ["Presence Of excess granulation tissues in wounds"],
    singleImg: [""],
    id: ["2"],
  },
  {
    heading: "Scarring",
    opt: [
      "Absent Scarring Or Pigmentary Change Only",
      "Mild To Moderate Scarring Localised To Lesions",
      "Severe Extensive Atrophic Scarring",
    ],
    mapping: ["-", "+", "++"],
    imgs: ["SC1", "SC2", "SC3"],
    size: ["32%","32%","32%"],
    cardheight: ["100%"],
    imageheight: ["83%"],
    subtitle: ["Absent scarring or pigmentary change only", "Mild to Moderate scarring localised to lesions", "Severe extensive atrophic scarring"],
    title: [""],
    singleImg: [""],
    id: ["3"],
  },
  {
    heading: "Milia",
    opt: ["Absent", "Milia Localised To Scars", "Widespread Milia"],
    mapping: ["-", "+", "++"],
    imgs: ["MI3", "MI1", "MI2"],
    size: ["32%","32%","32%"],
    cardheight: ["100%"],
    imageheight: ["92%"],
    subtitle: ["Localised Milia", "Widespread Milia"],
    title: [""],
    singleImg: [""],
    id: ["4"],
  },
  {
    heading: "Nail Dystrophy",
    opt: [
      "No Dystrophic Nails",
      "1-9 Dystrophic Nails",
      "10 Or More Dystrophic Nails",
    ],
    mapping: ["-", "+", "++"],
    imgs: ["ND12", "ND10", "ND9"],
    size: ["32%","32%","32%"],
    cardheight: ["100%"],
    imageheight: ["98.5%"],
    subtitle: ["", "", "", "", ""],
    title: ["Presence Of nail dystrophy characterized by thickening, deformity or discolouration"],
    singleImg: [""],
    id: ["5"],
  },
  {
    heading: "Nail Loss",
    opt: [
      "No Loss Of Nails",
      "Loss Of Fewer Than 10 Nails",
      "Loss Of 10 Or More Nails",
    ],
    mapping: ["-", "+", "++"],
    imgs: ["NL9", "NL7", "NL8"],
    size: ["32%","32%","32%"],
    cardheight: ["70%"],
    imageheight: ["98.5%"],
    subtitle: ["", "", "", "", ""],
    title: ["Examples Of Nail Loss"],
    singleImg: [""],
    id: ["6"],
  },
  {
    heading: "Mucosal Erosions",
    opt: [
      "Absent",
      "Occasional Erosions",
      "Frequent Or Persistent Erosions",
    ],
    mapping: ["-", "+", "++"],
    imgs: ["ME6", "ME4", "ME5"],
    size: ["14%","31%","52%"],
    cardheight: ["87%"],
    imageheight: ["98.5%"],
    subtitle: ["", "", "", "", ""],
    title: ["Examples Of Mucosal Erosions"],
    singleImg: [""],
    id: ["7"],
  },
  {
    heading: "Eye Involvement",
    opt: [
      "None",
      "Moderate: Recurrent Corneal Erosions",
      "Severe: Granulations Or Scarring (Eg Symblepharon)",
    ],
    mapping: ["-", "+", "++"],
    imgs: ["EI12_with_border", "EI3", "EI9_with_border"],
    size: ["12%","22%","63%"],
    cardheight: ["85%"],
    imageheight: ["90%"],
    subtitle: ["Moderate Eye Involvement", "Severe: Granulation", "Severe: Scarring, eg symblepharon"],
    title: [""],
    singleImg: [""],
    id: ["8"],
  },
  {
    heading: "Hoarseness",
    opt: ["Absence Of Hoarseness", "Presence Of Hoarseness"],
    mapping: ["-", "+", "++"],
    imgs: ["RT2", "RT1"],
    size: ["48%","48%"],
    cardheight: ["100%"],
    imageheight: ["92%"],
    subtitle: ["Severe Respiratory tract involvement"],
    title: [""],
    singleImg: [""],
    id: ["9"],
  },
  {
    heading: "Microstomia Or Ankyloglossia",
    opt: ["Absent", "Present"],
    mapping: ["-", "+", "++"],
    imgs: ["MA2", "MA1"],
    size: ["48%","48%"],
    cardheight: ["100%"],
    imageheight: ["88%"],
    subtitle: ["Microstomia With narrwing Of oral aperture as well as ankyloglossia With severe limitation Of toungue protrusion"],
    title: [""],
    singleImg: [""],
    id: ["10"],
  },
  {
    heading: "Poor Dental Enamel",
    opt: ["Normal", "Deficient enamel", "Not Applicable"],
    mapping: ["-", "+", "++"],
    imgs: ["DE5", "DE4", "DE5"],
    size: ["22%","52.5%","22%"],
    cardheight: ["100%"],
    imageheight: ["98.5%"],
    subtitle: ["", "", "", "", ""],
    title: ["Deficient dental enamel With yellow pitted teeth. Dental caries should be disregarded"],
    singleImg: [""],
    id: ["11"],
  },
  {
    heading: "Keratoderma",
    opt: ["No Keratoderma", "Moderate Keratoderma", "Severe Keratoderma"],
    mapping: ["-", "+", "++"],
    imgs: ["PK3", "PK1", "PK4"],
    size: ["32%","32%","32%"],
    cardheight: ["100%"],
    imageheight: ["92%"],
    subtitle: ["Moderate Keratoderma", "Severe Keratoderma"],
    title: [""],
    singleImg: [""],
    id: ["12"],
  },
  {
    heading: "Chronic Wounds",
    opt: ["Absent", "Moderate", "Severe"],
    mapping: ["-", "+", "++"],
    imgs: ["CW8_withoutborder", "CW7_withoutborder", "CW6"],
    size: ["15%","22%","60%"],
    cardheight: ["100%"],
    imageheight: ["86%"],
    subtitle: ["Moderate: Limited wounds lasting weeks", "Severe: more than limited wounds lasting months", "Severe: larger wounds lasting months"],
    title: [""],
    singleImg: [""],
    id: ["13"],
  },
  {
    heading: "Syndactyly",
    opt: ["Absence Of Syndactyly", "Moderate Syndactyly", "Severe Syndactyly"],
    mapping: ["-", "+", "++"],
    imgs: ["SY6", "SY5", "SY2"],
    size: ["32%","32%","32%"],
    cardheight: ["70%"],
    imageheight: ["92%"],
    subtitle: ["Moderate Syndactyly", "Severe Syndactyly"],
    title: [""],
    singleImg: [""],
    id: ["14"],
  },
  {
    heading: "Alopecia",
    opt: ["Absence Of Alopecia", "Moderate Alopecia", "Severe Alopecia"],
    mapping: ["-", "+", "++"],
    imgs: ["AL4", "AL3", "AL2"],
    size: ["32%","32%","32%"],
    cardheight: ["80%"],
    imageheight: ["90%"],
    subtitle: ["Moderate Alopecia", "Severe Alopecia"],
    title: [""],
    singleImg: [""],
    id: ["15"],
  },
  {
    heading: "Poikiloderma",
    opt: ["Absent", "Present"],
    mapping: ["-", "+", "++"],
    imgs: ["PO6", "PO"],
    size: ["20%","78%"],
    cardheight: ["100%"],
    imageheight: ["98.5%"],
    subtitle: ["", "", "", "", ""],
    title: ["Poikiloderma characterized by hyperpigmentation, telangiectasia and atrophy"],
    singleImg: [""],
    id: ["16"],
  },
  {
    heading: "Relative Growth Failure",
    opt: ["Absent", "Moderate", "Severe"],
    mapping: ["-", "+", "++"],
    imgs: ["RG1", "RG2", "RG3"],
    size: ["32%","32%","32%"],
    cardheight: ["100%"],
    imageheight: ["90%"],
    subtitle: ["No growth failure", "Moderate growth failure", "Severe growth failure"],
    title: [""],
    singleImg: [""],
    id: ["17"],
  },
  {
    heading: "Survival After 2 Yrs",
    opt: ["Did Not Survive", "Survived", "Alive And Under 2"],
    mapping: ["-", "+", "++"],
    imgs: ["MIA", "MIA", "MIA"],
    size: ["32%","32%","32%"],
    cardheight: ["70%"],
    imageheight: ["96.5%"],
    subtitle: ["", "", "", "", ""],
    title: [""],
    singleImg: [""],
    id: ["18"],
  },
  {
    heading: "Parents Affected",
    opt: ["Parents Not Affected", "Either Parent Affected", "Unknown"],
    mapping: ["-", "+", "++"],
    imgs: ["PA4", "PA5", "PA6"],
    size: ["32%","32%","32%"],
    cardheight: ["90%"],
    imageheight: ["90%"],
    subtitle: ["Parents Not Effected", "Either Parent Effected By EB", "Parental History Not Known"],
    title: [""],
    singleImg: [""],
    id: ["19"],
  },
];